apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  DATA_MICROSERVICE: MyOtherMicroservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: jchuah04/myapp:latest
        envFrom:
        - configMapRef:
            name: myapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" 
        ports:
        - containerPort: 3000