name: Build and Test RESTful Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build -t docker build -t my-nodejs-app .
      
    - name: Run the Docker container
      run: docker run -p 3000:3000 my-nodejs-app
      
    - name: Test the RESTful service
      run: |
        # Wait for the container to start up
        sleep 5
        
        # Send a GET request to the service
        response=$(curl "http://localhost:31234/fib?length=5")
        
        # Check that the response is "[0,1,1,2,3]"
        if [ "$response" == "[0,1,1,2,3]" ]; then
          echo "Test passed!"
        else
          echo "Test failed. Expected '[0,1,1,2,3]', got '$response'"
          exit 1
        fi